var inputDataJsonSample =    {
    "totals": {
      "ast": {
        "SourceUnit": 1,
        "PragmaDirective": 4,
        "Pragma:solidity:^0.5.5": 1,
        "Pragma:experimental:ABIEncoderV2": 1,
        "ContractDefinition": 2,
        "ContractDefinition:Contract": 1,
        "ContractDefinition:BaseContracts": 0,
        "StructDefinition": 3,
        "VariableDeclaration": 100,
        "ArrayTypeName": 8,
        "ElementaryTypeName": 73,
        "StateVariableDeclaration": 18,
        "UserDefinedTypeName": 22,
        "UserDefinedTypeName:ChannelPolicy": 3,
        "EventDefinition": 3,
        "ParameterList": 27,
        "FunctionCall": 168,
        "Identifier": 215,
        "FunctionCall:MemberAccess": 18,
        "MemberAccess": 88,
        "StringLiteral": 27,
        "Mapping": 1,
        "UserDefinedTypeName:TransactionValue": 3,
        "FunctionDefinition": 30,
        "FunctionDefinition:View": 2,
        "FunctionDefinition:Private": 4,
        "Parameter": 27,
        "Block": 21,
        "VariableDeclarationStatement": 15,
        "ReturnStatement": 11,
        "FunctionDefinition:Pure": 8,
        "UserDefinedTypeName:TransactionSummary": 5,
        "FunctionCall:Regular": 21,
        "VariableDeclaration:Memory": 1,
        "NewExpression": 1,
        "ForStatement": 5,
        "NumberLiteral": 17,
        "BinaryOperation": 31,
        "ExpressionStatement": 37,
        "UnaryOperation": 17,
        "IndexAccess": 11,
        "FunctionDefinition:Internal": 9,
        "InlineAssemblyStatement": 1,
        "AssemblyBlock": 1,
        "AssemblyAssignment": 3,
        "AssemblyCall": 10,
        "DecimalNumber": 4,
        "TupleExpression": 1,
        "IfStatement": 6,
        "BooleanLiteral": 5,
        "ElementaryTypeNameExpression": 5,
        "FunctionDefinition:Public": 4,
        "EmitStatement": 3,
        "FunctionDefinition:Payable": 2,
        "FunctionDefinition:External": 1
      },
      "sloc": {
        "total": 220,
        "source": 171,
        "comment": 61,
        "single": 61,
        "block": 0,
        "mixed": 45,
        "empty": 33,
        "todo": 0,
        "blockEmpty": 0,
        "commentToSourceRatio": 0.3567251461988304
      },
      "nsloc": {
        "total": 220,
        "source": 171,
        "comment": 61,
        "single": 61,
        "block": 0,
        "mixed": 45,
        "empty": 33,
        "todo": 0,
        "blockEmpty": 0,
        "commentToSourceRatio": 0.3567251461988304
      },
      "complexity": {
        "perceivedNaiveScore": 534
      },
      "summary": {
        "perceivedComplexity": "5",
        "size": "1",
        "numLogicContracts": "1",
        "interfaceRisk": "2",
        "inlineDocumentation": "4",
        "compilerFeatures": "2",
        "compilerVersion": "1"
      },
      "num": {
        "astStatements": 1022,
        "contractDefinitions": 2,
        "contracts": 1,
        "libraries": 0,
        "interfaces": 0,
        "imports": 0,
        "functionsPublic": 5,
        "functionsPayable": 2,
        "assemblyBlocks": 1
      },
      "capabilities": {
        "solidityVersions": [
          "^0.5.5"
        ],
        "assembly": true,
        "experimental": [
          "ABIEncoderV2"
        ],
        "canReceiveFunds": true
      }
    },
    "avg": {
      "ast": {
        "SourceUnit": 1,
        "PragmaDirective": 4,
        "Pragma:solidity:^0.5.5": 1,
        "Pragma:experimental:ABIEncoderV2": 1,
        "ContractDefinition": 2,
        "ContractDefinition:Contract": 1,
        "ContractDefinition:BaseContracts": 0,
        "StructDefinition": 3,
        "VariableDeclaration": 100,
        "ArrayTypeName": 8,
        "ElementaryTypeName": 73,
        "StateVariableDeclaration": 18,
        "UserDefinedTypeName": 22,
        "UserDefinedTypeName:ChannelPolicy": 3,
        "EventDefinition": 3,
        "ParameterList": 27,
        "FunctionCall": 168,
        "Identifier": 215,
        "FunctionCall:MemberAccess": 18,
        "MemberAccess": 88,
        "StringLiteral": 27,
        "Mapping": 1,
        "UserDefinedTypeName:TransactionValue": 3,
        "FunctionDefinition": 30,
        "FunctionDefinition:View": 2,
        "FunctionDefinition:Private": 4,
        "Parameter": 27,
        "Block": 21,
        "VariableDeclarationStatement": 15,
        "ReturnStatement": 11,
        "FunctionDefinition:Pure": 8,
        "UserDefinedTypeName:TransactionSummary": 5,
        "FunctionCall:Regular": 21,
        "VariableDeclaration:Memory": 1,
        "NewExpression": 1,
        "ForStatement": 5,
        "NumberLiteral": 17,
        "BinaryOperation": 31,
        "ExpressionStatement": 37,
        "UnaryOperation": 17,
        "IndexAccess": 11,
        "FunctionDefinition:Internal": 9,
        "InlineAssemblyStatement": 1,
        "AssemblyBlock": 1,
        "AssemblyAssignment": 3,
        "AssemblyCall": 10,
        "DecimalNumber": 4,
        "TupleExpression": 1,
        "IfStatement": 6,
        "BooleanLiteral": 5,
        "ElementaryTypeNameExpression": 5,
        "FunctionDefinition:Public": 4,
        "EmitStatement": 3,
        "FunctionDefinition:Payable": 2,
        "FunctionDefinition:External": 1
      },
      "sloc": {
        "total": 220,
        "source": 171,
        "comment": 61,
        "single": 61,
        "block": 0,
        "mixed": 45,
        "empty": 33,
        "todo": 0,
        "blockEmpty": 0,
        "commentToSourceRatio": 0.3567251461988304
      },
      "nsloc": {
        "total": 220,
        "source": 171,
        "comment": 61,
        "single": 61,
        "block": 0,
        "mixed": 45,
        "empty": 33,
        "todo": 0,
        "blockEmpty": 0,
        "commentToSourceRatio": 0.3567251461988304
      },
      "complexity": {
        "perceivedNaiveScore": 801
      },
      "summary": {
        "size": "1",
        "perceivedComplexity": "6",
        "numLogicContracts": "1",
        "interfaceRisk": "2",
        "inlineDocumentation": "4",
        "compilerFeatures": "1",
        "compilerVersion": "1"
      },
      "num": {
        "astStatements": 1022,
        "contractDefinitions": 2,
        "contracts": 1,
        "libraries": 0,
        "interfaces": 0,
        "imports": 0,
        "functionsPublic": 5,
        "functionsPayable": 2,
        "assemblyBlocks": 1
      },
      "capabilities": {
        "assembly": true,
        "canReceiveFunds": true
      }
    },
    "num": {
      "sourceUnits": 1,
      "metrics": 1,
      "duplicates": 0,
      "errors": 0
    }
  }


